/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/scene/LevelSelect.ls
 */
export class LevelSelectRTBase extends Laya.Scene {
    public item0Tab!: Laya.Tab;
    public levelstack!: Laya.ViewStack;
    public LevelList!: Laya.List;
}

